version: '3.9'
services:
  build:
    image: mixcons-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/project
      - build_packages:/build_packages:ro
      - vcpkg_packages:/vcpkg_packages
    environment:
      - VERSION=1.0.0
    working_dir: /project
volumes:
  build_packages:
  vcpkg_packages:
